### ISSUE TITLE
Feature request: make $request available in getOptionsCallable

### ISSUE THREAD

**Issue by vixducis** [thephpleague/route#304] opened 2021-07-14 18:19 UTC
Lately, the getOptionsCallable was implemented as part of OptionsHandlerInterface (which is a pretty nice way to handle OPTIONS requests). However, I feel like it could be even better when the `$request` is passed on top of `$methods`. Some headers that need to be returned, like `Access-Control-Allow-Origin` and `Access-Control-Allow-Headers` depend on the request headers. This scenario currently needs some workaround by injecting the request into the Strategy, which is sub-ideal.

This seems pretty doable, I think, as `getOptionsCallable` is called by `buildOptionsRoutes`, which on it's turn is called by `prepareRoutes`, which has the $request parameter available.

**Comment by philipobenito** [comment] 2021-07-14 18:21
Want to have a go at a PR? Try not to introduce a breaking change if possible, if that turns out to be quite difficult then we can discuss it.

**Comment by philipobenito** [comment] 2021-07-21 12:24
I've just been playing around with things for 6.x and realised the callable returned from `getOptionsCallable` is already passed the request object, this is because it's already a controller, I imagine this isn't clear as the example in `JsonStrategy` doesn't define a $request argument since it doesn't need it.

I think renaming `getOptionsCallable` to `getOptionsController` will make things a little clearer with some better docs too.

Similarly, all the other strategy methods also already have access to the request object since the middleware they return is passed a request object when invoked.

So if in your `getOptionsCallable` method you define something like this, it'll work:

```php
public function getOptionsCallable(): callable
{
    return function (ServerRequestInterface $request) {
        // do something with $request and return a response
    };
}
```

I'll close this as it is by design, sorry I didn't realise earlier.

**Closed as completed by philipobenito** 2021-07-21 12:24 UTC
