### ISSUE TITLE
Route::getCallable doesn't work if handler is an alias of an instance of a callable class

### ISSUE THREAD

**Issue by pfazzi** [thephpleague/route#281] opened 2020-04-18 11:01 UTC
In a PSR-11 compliant Container i may define services using IDs instead of the FQCN. This is usefull when a class has multiple instances in the container. Let's consider the following definition:
```php
'controller.project.create_project' => GenericCreateController::class
```
Where `GenericCreateController` is an invokable class.

If I define the following route:
```php
$router->post('/projects', 'controller.project.create_project');
```
it won't work. ATM I have to define it as:
```php
$router->post('/projects', ['controller.project.create_project', '__invoke']);
```
It would be nice to simply use the class alias without the need to specify the `__invoke` method.

**Comment by memran** [comment] 2020-05-17 20:01
i think You can try to use custom strategy. You need to set container on strategy by calling method 'setContainer'.

for more help please check here https://route.thephpleague.com/4.x/dependency-injection/.

**Comment by philipobenito** [comment] 2020-05-18 07:12
Duplicate of #263

**Closed by philipobenito** 2020-05-18 07:12 UTC
