### ISSUE TITLE
NotFoundationException: Not Found in vendor/league/route/src/Dispatcher.php:68

### ISSUE THREAD

**Issue by JayyWalker** [thephpleague/route#146] opened 2017-04-04 12:21 UTC
Hey guys, I've seen this [issue](https://github.com/thephpleague/route/issues/126), but the solution did not work for me.

My `REQUEST_URI` is fine and my base uri is `lux.192.168.0.47.nip.io`. It is definitely found because the controller's response returns the right content, but the NotFoundException is still logged.

My route setup:
``` php
$app = new Lux\App;

$app = new Lux\App;

$app->get('/', '\Lux\Controller\TestController::__invoke');

$app->run();
```

I am using PHP-DI for the container.
My  which is called in the Lux\App construct:
``` php
    protected function buildContainer()
    {
        $builder = new ContainerBuilder();

        $builder->addDefinitions(
            [
                'request' => function() {
                    return \Zend\Diactoros\ServerRequestFactory::fromGlobals();
                },

                'response' => object(\Zend\Diactoros\Response::class),

                'emitter' => object(SapiEmitter::class),

                'router' => function (ContainerInterface $c) {
                    $router = new \League\Route\RouteCollection($c);
                    $router->setStrategy(new \Lux\Http\DependancyInjectionStrategy);

                    return $router;
                }
            ]
        );

        $this->container = $builder->build();
    }
```

**Comment by philipobenito** [comment] 2017-04-04 12:35
What happens, if you remove `::__invoke` from the route callable, I don't know PHP-DI very well but I suspect you might have some callable inception going on here as if the class has a magic `__invoke` method, the class is already callable container may well be invoking that method regardless of whether a route is matched.

**Comment by JayyWalker** [comment] 2017-04-04 20:54
@philipobenito When I remove `::__invoke`, I get this error:

``` log
2017/04/04 21:51:38 [error] 2202#0: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Could not resolve a callable for this route in /home/user/projects/lux/project/vendor/league/route/src/Route.php:93
Stack trace:
#0 /home/user/projects/lux/project/src/Http/DependancyInjectionStrategy.php(36): League\Route\Route->getCallable()
#1 /home/user/projects/lux/project/vendor/league/route/src/Middleware/ExecutionChain.php(41): Lux\Http\DependancyInjectionStrategy->Lux\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Closure))
#2 /home/user/projects/lux/project/vendor/league/route/src/Middleware/ExecutionChain.php(23): League\Route\Middleware\ExecutionChain->League\Route\Middleware\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#3 /home/user/projects/lux/project/vendor/league/route/src/RouteCollection.php(130): League\Route\Middleware\ExecutionChain->execute(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#4 /home/user/projects/lux/p" while reading response header from upstream, client: 192.168.0.28, server: lux.192.168.0.28.nip.io, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "lux.192.168.0.28.nip.io"

```

**Comment by philipobenito** [comment] 2017-04-05 07:55
I can'r reproduce anything like this, I'd need more context to help you, can you gist the code or something?

I'm pretty certain this isn't a bug though.

**Comment by JayyWalker** [comment] 2017-04-10 11:35
So I created a separate project just to reproduce this issue and ran it using the PHP server `php -S 0.0.0.0:3000 -t public`. It's fine, no issues.

It's only when I run it on my nginx server that I see the issue. I'm not sure if this is also an issue on Apache as I don't have it installed on my server.

**Comment by philipobenito** [comment] 2017-04-10 12:32
I'm really struggling to help you here as you're not providing me with very much context at all.

There is an issue when using Apache and your base path is not the root URI, solution shown in #126.

But the issue here must be with your NGINX config as you have said, it works fine with PHP built in web server. I also cannot reproduce under my own NGINX set up.

For now, I am going to close this issue as I am convinced this is not a bug. If you need help with implementation then you will need to provide me with more context as I said above. A gist or something similar.

**Closed by philipobenito** 2017-04-10 12:32 UTC
